### ISSUE TITLE
Couldn't load the model

### ISSUE THREAD

**Issue by Bk073** [ravsau/langchain-notes#1]
I tried using the code to load a file with .bin extension downloaded from GPT4ALL, but I am getting this error:
```

ValidationError: 1 validation error for LlamaCpp
__root__
  Could not load Llama model from path: /home/bishwa/llm/models/llama-2-7b-chat.ggmlv3.q4_0.bin. Received error  (type=value_error
```
I even tried downloading gguf model but still running into error.

**Comment by ravsau** [comment]
Are you trying to use GPU inference? 


For GPU inference the install command is 
``` CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python```

**Comment by Bk073** [comment]
Yes, I tried for both in GPU and CPU. For GPU I installed using `CMAKE_ARGS="-DLLAMA_CUBLAS=on" FORCE_CMAKE=1 pip install llama-cpp-python`. But the problem is same. 

I even tried this: 

`
from llama_cpp import Llama

model_path = "/home/bishwa/llm/models/mpt-7b-chat-q4_0.gguf"

llm = Llama(model_path=model_path)
`

**Comment by ravsau** [comment]
I followed the same steps again and was getting the same error. This command fixed the issue for me. Can you try this 

```
pip install llama-cpp-python --force-reinstall --upgrade --no-cache-dir
```

**Comment by Bk073** [comment]
I think it's the issue with the model that I am using. Previously, I tried models from Gpt4All but later I downloaded models from huggingface, the issue is gone. 

Thanks again for your help.
